# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10         # use the latest tag shown on GitHub
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black